-- Basic

require("core.constants")
require("core.variables")
require("core.utils")
require("core.plugins")
require("core.snippets")
require("core.mappings")
require("core.config")
require("core.commands")
require("core.colors")
require("core.mason")
require("core.macros")
require("core.autocmd")
-- Plugins
require("plugins.substitute")
require("plugins.oil")
require('plugins.text-objects')
require("plugins.toggleterm")
require("plugins.gitsigns")
require("plugins.todo-comments")
require("plugins.dapui")
require("plugins.neodev")
require("plugins.nvimtree")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.lspkind")
require("plugins.cmp")
require("plugins.trouble")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.dashboard")
require("plugins.comment")
require("plugins.bufferline")
require("plugins.iconpicker")
require("plugins.dressing")
require("plugins.sessionmanager")
require("plugins.rustaceanvim")
-- require("plugins.rusttools")
require("plugins.boole")
-- require("plugins.whichkey")
require("plugins.colorizer")
-- require("plugins.lsp-progress")
require("plugins.lsp-signature")
require("plugins.outline")
require("plugins.fidget")
require("plugins.ts-autotag")
-- require("plugins.hydra")
require("plugins.conform")
require("plugins.neotest")
-- require("plugins.multicursors")

-- require("plugins.formatter")
-- require("plugins.blankline")
-- require("plugins.notify")
-- require("plugins.hologram")
-- require("plugins.better-n")
-- require("plugins.fterm")
-- TODO set keymap to delete without putting stuff to register
